import {
  UtensilsCrossed,
  Car,
  ShoppingBag,
  Receipt,
  Film,
  HeartPulse,
  GraduationCap,
  Home,
  Briefcase,
  Gift,
  Plane,
  Coffee,
  PiggyBank,
  Wifi,
  Fuel,
  Dumbbell,
  Baby,
  PawPrint,
  TrendingUp,
  Wallet,
  CreditCard,
  ShoppingCart,
  Banknote,
  Circle,
  Target,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  food: UtensilsCrossed,
  "utensils-crossed": UtensilsCrossed,
  coffee: Coffee,
  transport: Car,
  car: Car,
  fuel: Fuel,
  shopping: ShoppingBag,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  bills: Receipt,
  receipt: Receipt,
  entertainment: Film,
  film: Film,
  health: HeartPulse,
  "heart-pulse": HeartPulse,
  education: GraduationCap,
  "graduation-cap": GraduationCap,
  housing: Home,
  home: Home,
  salary: Briefcase,
  briefcase: Briefcase,
  gift: Gift,
  travel: Plane,
  plane: Plane,
  savings: PiggyBank,
  "piggy-bank": PiggyBank,
  wifi: Wifi,
  fitness: Dumbbell,
  dumbbell: Dumbbell,
  family: Baby,
  baby: Baby,
  pet: PawPrint,
  "paw-print": PawPrint,
  investment: TrendingUp,
  "trending-up": TrendingUp,
  wallet: Wallet,
  card: CreditCard,
  "credit-card": CreditCard,
  cash: Banknote,
  banknote: Banknote,
  circle: Circle,
  target: Target,
  emergency_fund: ShieldCheck,
  "emergency-fund": ShieldCheck,
  shield: ShieldCheck,
};

export function getCategoryIcon(icon?: string | null): LucideIcon {
  if (!icon) return Circle;
  return ICON_MAP[icon.toLowerCase()] ?? Circle;
}
